export default{
    MODE_AUTO:{
      src: "assets/img/sel_mode/program_all_icon_auto@2x.png",
      text: "智能洗",
      mode: 1,
      dec: "智能分析，自动选择，最佳的清洗方式",
      additionalMode: 0,
      time: '--',
      temp: '--',
      isDiyMode: false,
      stageStep:[
        {name:'预洗',value:1},{name:'主洗',value:2},{name:'漂洗',value:3},{name:'干燥',value:4}],
    },
    MODE_INTENSIVE:{
      src: "assets/img/sel_mode/program_all_icon_intensive@2x.png",
      text: "强力洗",
      mode: 2,
      dec: "",
      additionalMode: 0,
      showAdditional: true,
      additionalArr:[
        {additionalMode:0,time:110,temp:72,title:'不附加',dec:'',isActive:false},
        {additionalMode:5,time:120,temp:72,title:'加强除菌',dec:'餐具杀菌，清洁效果好',isActive:false},
        {additionalMode:7,time:98,temp:72,title:'少量',dec:'餐具较少的情况下，叠加少量可以省水省电',isActive:false},
      ],
      time: 110,
      temp: 72,
      isDiyMode: false,
      stageStep:[{name:'预洗',value:1},{name:'主洗',value:2},{name:'漂洗',value:3},{name:'干燥',value:4}],
    },
    MODE_NORMAL:{
      src: "assets/img/sel_mode/program_all_icon_normal@2x.png",
      text: "即时洗",
      mode: 3,
      dec: "",
      additionalMode: 0,
      showAdditional: true,
      additionalArr:[
        {additionalMode:0,time:60,temp:60,title:'不附加',dec:'',isActive:false},
        {additionalMode:5,time:74,temp:70,title:'加强除菌',dec:'餐具杀菌，清洁效果好',isActive:false},
        {additionalMode:7,time:59,temp:60,title:'少量',dec:'餐具较少的情况下，叠加少量可以省水省电',isActive:false},
      ],
      time: 60,
      temp: 60,
      isDiyMode: false,
      stageStep:[{name:'预洗',value:1},{name:'主洗',value:2},{name:'漂洗',value:3},{name:'干燥',value:4}],
    },
    MODE_ECO:{
      src: "assets/img/sel_mode/program_all_icon_ECO@2x.png",
      text: "节能洗",
      mode: 4,
      dec: "",
      additionalMode: 0,
      showAdditional: true,
      additionalArr:[
        {additionalMode:0,time:190,temp:70,title:'不附加',dec:'',isActive:false},
        {additionalMode:3,time:138,temp:70,title:'加速',dec:'加速清洗可以节省时间',isActive:false},
        {additionalMode:5,time:200,temp:70,title:'加强除菌',dec:'餐具杀菌，清洁效果好',isActive:false},
        {additionalMode:7,time:160,temp:70,title:'少量',dec:'餐具较少的情况下，叠加少量可以省水省电',isActive:false},
      ],
      time: 190,
      temp: 70,
      isDiyMode: false,
      stageStep:[{name:'预洗',value:1},{name:'主洗',value:2},{name:'漂洗',value:3},{name:'干燥',value:4}],
    },
    MODE_GLASS:{
      src: "assets/img/sel_mode/program_all_icon_glass@2x.png",
      text: "玻璃洗",
      mode: 5,
      dec: "",
      additionalMode: 0,
      showAdditional: true,
      additionalArr:[
        {additionalMode:0,time:56,temp:60,title:'不附加',dec:'',isActive:false},
        {additionalMode:5,time:60,temp:65,title:'加强除菌',dec:'餐具杀菌，清洁效果好',isActive:false},
        {additionalMode:7,time:48,temp:60,title:'少量',dec:'餐具较少的情况下，叠加少量可以省水省电',isActive:false},
      ],
      time: 56,
      temp: 60,
      isDiyMode: false,
      stageStep:[{name:'主洗',value:2},{name:'漂洗',value:3},{name:'干燥',value:4}],
    },
    MODE_RAPID:{
      src: "assets/img/sel_mode/program_all_icon_rapid@2x.png",
      text: "超快洗",
      mode: 7,
      dec: "清污餐具，短时间洗涤",
      additionalMode: 0,
      time: 29,
      temp: 66,
      isDiyMode: false,
      stageStep:[{name:'主洗',value:2},{name:'漂洗',value:3}],
    },
    MODE_SOAK:{
      src: "assets/img/sel_mode/program_all_icon_pre-wash_Soak@2x.png",
      text: "预冲洗",
      mode: 8,
      dec: "快速冲洗餐具表面",
      additionalMode: 0,
      time: 12,
      temp: 36,
      isDiyMode: false,
      stageStep:[{name:'预洗',value:1}],
    },
    MODE_90MIN:{
      src: "assets/img/sel_mode/90min@2x.png",
      text: "90min洗",
      mode: 9,
      additionalMode: 0,
      time: 90,
      temp: 65,
      isDiyMode: false,
      stageStep:[{name:'主洗',value:2},{name:'漂洗',value:3},{name:'干燥',value:4}],
    },
    MODE_CLEAN:{
      src: "assets/img/sel_mode/program_all_icon_self-cleaning@2x.png",
      text: "自清洁",
      mode: 10,
      additionalMode: 0,
      dec: "配合专用清洗剂，定期保养",
      time: 75,
      temp: 70,
      isDiyMode: false,
      stageStep:[{name:'主洗',value:2},{name:'漂洗',value:3},{name:'干燥',value:4}],
    },
    MODE_FRUIT:{
      src: "assets/img/sel_mode/program_all_icon_fruits@2x.png",
      text: "水果洗",
      mode: 11,
      additionalMode: 0,
      time: 12,
      temp: 36,
      isDiyMode: false,
      stageStep:[{name:'预洗',value:1}],
    },
    MODE_DIY:{
      src: "assets/img/sel_mode/setting_diy.png",
      text: "自定义洗",
      mode: 12,
      additionalMode: 0,
      time: "-:--",
      temp: "--",
      isDiyMode: true,
      stageStep:[{name:'预洗',value:1}],
      diyProgram:[
        {name:'DIY1',mainTemp:0, washTemp:0,mainTempRange:[60],washTempRange:[50],stageStep:[{name:'预洗',value:1}]},
        {name:'DIY2',mainTemp:0, washTemp:0,mainTempRange:[60],washTempRange:[50],stageStep:[{name:'预洗',value:1}]},
        {name:'DIY3',mainTemp:0, washTemp:0,mainTempRange:[45,50,55,60,65],washTempRange:[50,55,60,65,70],stageStep:[{name:'预洗',value:1},{name:'主洗',value:2},{name:'漂洗',value:3},{name:'干燥',value:4}]},
        {name:'DIY4',mainTemp:0, washTemp:0,mainTempRange:[45,50,55,60,65],washTempRange:[50,55,60,65,70],stageStep:[{name:'预洗',value:1},{name:'主洗',value:2},{name:'漂洗',value:3},{name:'干燥',value:4}]},
        {name:'DIY5',mainTemp:0, washTemp:0,mainTempRange:[45,50,55,60,65],washTempRange:[50,55,60,65,70],stageStep:[{name:'预洗',value:1},{name:'主洗',value:2},{name:'漂洗',value:3},{name:'干燥',value:4}]},
        {name:'DIY6',mainTemp:0, washTemp:0,mainTempRange:[45,50,55,60,65],washTempRange:[50,55,60,65,70],stageStep:[{name:'预洗',value:1},{name:'主洗',value:2},{name:'漂洗',value:3},{name:'干燥',value:4}]},
      ],
      diySelectIndex:0,
    },

    getSupportMode: function(){
      var self = this;
      var modeArr = [
        self.MODE_INTENSIVE,
        self.MODE_RAPID,
        self.MODE_ECO,
        self.MODE_NORMAL,
        self.MODE_GLASS,
        self.MODE_SOAK,
        self.MODE_CLEAN,
      ]
      return modeArr;
    }
}